### ISSUE TITLE
Issue with sankee.Dataset()

### ISSUE THREAD

**Issue by Daniel-Trung-Nguyen** [aazuspan/sankee#14]
I am running one of the examples on Google Colab and encountered this problem:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-13-ff7c70bf4b70> in <module>()
----> 1 dataset = sankee.Dataset(collection_name="custom", band=band, labels=labels, palette=palette)

AttributeError: module 'sankee' has no attribute 'Dataset'

![image](https://user-images.githubusercontent.com/22897462/142975456-40641cb9-b553-4ba8-93a9-b79446a9d2c1.png)

**Comment by aazuspan** [comment]
You're right, that was broken! This should be fixed with `0.0.7`. Thanks for reporting it!
