### ISSUE TITLE
Making sankee available on conda-forge

### ISSUE THREAD

**Issue by giswqs** [aazuspan/sankee#2]
Thank you for developing this nice package! Have you considered making it available on [conda-forge](https://conda-forge.org/) channel? I would love to incorporate sankee into the geemap toolbar and develop an interactive GUI for this so that users can create sankee plots without coding. Pull request is also welcome. 

[Here](https://youtu.be/NNWhz7pqwCw) is a tutorial for publishing a Python package on conda-forge. I would be happy to help if needed.

**Comment by aazuspan** [comment]
@giswqs Thank you for the recommendation and the tutorial. sankee is now available on [conda-forge](https://anaconda.org/conda-forge/sankee). I'd be thrilled to have the package integrated in geemap, and I think a GUI is great idea. Please let me know if I can help with that process.

**Comment by giswqs** [comment]
@aazuspan Thanks a lot for making it available on conda-forge. I will try to implement the GUI sometime next week. 
https://github.com/giswqs/geemap/issues/427
