### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by giswqs** [aazuspan/sankee#43]
It seems the example no longer works. Getting `EEException: Element.propertyNames: Parameter 'element' is required.`

```python
import sankee
import ee

ee.Initialize()

sankee.datasets.LCMS_LC.sankify(
  years=[1990, 2000, 2010, 2020],
  region=ee.Geometry.Point([-122.192688, 46.25917]).buffer(2000),
  max_classes=3,
  title="Mt. St. Helens Recovery"
)
```

![image](https://github.com/aazuspan/sankee/assets/5016453/bae534eb-ba02-4b1f-af1e-55a8f7ceab46)

**Comment by aazuspan** [comment]
Good catch @giswqs, `sankee` was still using old LCMS dataset versions which were apparently causing some issues. I just updated the datasets to [v2022.8](https://developers.google.com/earth-engine/datasets/catalog/USFS_GTAC_LCMS_v2022-8) which seems to resolve this. I'll release those changes shortly. 

Thanks for letting me know!

**Comment by giswqs** [comment]
Thank you for the quick fix.
